# Generated by Django 5.2.15 on 2026-08-05 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiStudioTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('status', models.CharField(default='PENDING', max_length=10, verbose_name='状态(提交时快照)')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='请求参数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_gateway_tasks', to=settings.AUTH_USER_MODEL, verbose_name='提交用户')),
            ],
            options={
                'verbose_name': 'AI 网关任务',
                'verbose_name_plural': 'AI 网关任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
