# Generated by Django 6.0.6 on 2026-07-17 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('channel', models.CharField(choices=[('email', '邮件'), ('dingtalk', '钉钉'), ('feishu', '飞书')], max_length=20, verbose_name='通知渠道')),
                ('config', models.JSONField(default=dict, help_text='JSON格式的配置信息', verbose_name='配置信息')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警通知配置',
                'verbose_name_plural': '告警通知配置',
                'db_table': 'alert_notification_config',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='warning', max_length=20, verbose_name='告警级别')),
                ('condition_type', models.CharField(choices=[('log_level', '日志级别'), ('keyword', '关键词'), ('custom', '自定义条件')], default='log_level', max_length=50, verbose_name='条件类型')),
                ('condition_value', models.TextField(verbose_name='条件值')),
                ('channels', models.JSONField(default=list, help_text='JSON数组，可选值：email, dingtalk, feishu', verbose_name='通知渠道')),
                ('escalation_rules', models.JSONField(default=list, help_text='[{ "delay_minutes": 30, "level": "critical", "channels": [...] }]', verbose_name='升级规则')),
                ('silent_periods', models.JSONField(blank=True, default=list, help_text='[{ "start": "22:00", "end": "08:00" }]', verbose_name='静默时段')),
                ('suppression_window', models.IntegerField(default=5, help_text='相同告警在该时间窗口内只发送一次', verbose_name='抑制窗口(分钟)')),
                ('max_occurrences', models.IntegerField(default=10, help_text='超过此次数后自动抑制', verbose_name='最大触发次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_rules_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '告警规则',
                'verbose_name_plural': '告警规则',
                'db_table': 'alert_rule',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertSilence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='静默名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('match_pattern', models.TextField(blank=True, help_text='告警内容匹配模式（支持正则）', null=True, verbose_name='匹配模式')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_silences_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='silences', to='alert_system.alertrule', verbose_name='关联规则')),
            ],
            options={
                'verbose_name': '告警静默',
                'verbose_name_plural': '告警静默',
                'db_table': 'alert_silence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='warning', max_length=20, verbose_name='告警级别')),
                ('title', models.CharField(max_length=500, verbose_name='告警标题')),
                ('content', models.TextField(verbose_name='告警内容')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('sent', '已发送'), ('failed', '发送失败'), ('suppressed', '已抑制'), ('silenced', '已静默')], default='pending', max_length=20, verbose_name='状态')),
                ('channels', models.JSONField(default=list, verbose_name='发送渠道')),
                ('sent_channels', models.JSONField(default=list, verbose_name='已发送渠道')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('occurrences', models.IntegerField(default=1, verbose_name='发生次数')),
                ('first_occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='首次发生时间')),
                ('last_occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='最近发生时间')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='是否已确认')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='上下文信息')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_acknowledged', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts_resolved', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='alert_system.alertrule', verbose_name='关联规则')),
            ],
            options={
                'verbose_name': '告警历史',
                'verbose_name_plural': '告警历史',
                'db_table': 'alert_history',
                'ordering': ['-first_occurred_at'],
                'indexes': [models.Index(fields=['-last_occurred_at'], name='alert_histo_last_oc_a34eff_idx'), models.Index(fields=['status', 'level'], name='alert_histo_status_7104aa_idx'), models.Index(fields=['acknowledged', 'resolved'], name='alert_histo_acknowl_4c15ab_idx')],
            },
        ),
    ]
