# Generated by Django 5.2.15 on 2026-09-01 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_system', '0001_initial'),
        ('saas', '0007_role_data_scope_department_tenantmember_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='模板编码')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(help_text='支持 {placeholder} 占位符', verbose_name='内容')),
                ('html_content', models.TextField(blank=True, help_text='可选，前端富文本渲染；缺省时用 content', null=True, verbose_name='HTML 内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站内信模板',
                'verbose_name_plural': '站内信模板',
                'db_table': 'message_template',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='idx_msg_tpl_code_active')],
            },
        ),
        migrations.CreateModel(
            name='InAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='info', max_length=20, verbose_name='级别')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_app_messages', to='saas.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_messages', to=settings.AUTH_USER_MODEL, verbose_name='收件人')),
            ],
            options={
                'verbose_name': '站内信',
                'verbose_name_plural': '站内信',
                'db_table': 'in_app_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='idx_inapp_user_read'), models.Index(fields=['tenant', 'read_at'], name='idx_inapp_tenant_read')],
            },
        ),
    ]
