# Generated by Django 5.2.15 on 2026-09-01 01:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('event_version', models.PositiveIntegerField(default=1)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('aggregate_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('aggregate_sequence', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('trace_id', models.CharField(blank=True, max_length=100, null=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', '待投递'), ('COMPLETE', '已完成'), ('DEAD_LETTER', '死信')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('dead_lettered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='outbox_st_avail_idx')],
            },
        ),
        migrations.CreateModel(
            name='InboxReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='framework.outboxevent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('consumer_name', 'event'), name='uq_inbox_receipt_consumer_event')],
            },
        ),
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=100)),
                ('target_type', models.CharField(choices=[('LOCAL_CONSUMER', '本地消费'), ('EXTERNAL_BROKER', '外部消息中间件')], db_index=True, default='LOCAL_CONSUMER', max_length=20)),
                ('consumer_module', models.CharField(blank=True, max_length=100, null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', '待投递'), ('PROCESSING', '投递中'), ('DELIVERED', '已投递'), ('DEAD_LETTER', '死信')], db_index=True, default='PENDING', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('locked_by', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('dead_lettered_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='framework.outboxevent')),
            ],
            options={
                'ordering': ['available_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='deliv_st_avail_idx'), models.Index(fields=['locked_until'], name='deliv_lock_until_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'target_name'), name='uq_outbox_delivery_target')],
            },
        ),
    ]
