apiVersion: v1
kind: Namespace
metadata:
  name: django-saas
  labels:
    app.kubernetes.io/name: django-saas
    app.kubernetes.io/part-of: django-saas
    app.kubernetes.io/environment: production
