# Generated by Django 5.2.8 on 2026-05-29 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '新增'), ('UPDATE', '修改'), ('DELETE', '删除'), ('OTHER', '其他')], max_length=10, verbose_name='操作行为')),
                ('target_model', models.CharField(max_length=100, verbose_name='目标模型')),
                ('target_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标ID')),
                ('action_info', models.JSONField(blank=True, null=True, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='浏览器指纹')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志',
                'verbose_name_plural': '审计日志',
                'db_table': 'core_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
