# Generated by Django 5.2.8 on 2026-05-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, db_comment='头像', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
    ]
