# Generated by Django 5.2.15 on 2026-06-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_add_role_name_unique'),
        ('users', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='global_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_users', to='saas.role', verbose_name='全局角色'),
        ),
    ]
