# Generated by Django 6.0.6 on 2026-07-17 07:33

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_enhanced'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__action_5c03c3_idx',
            old_name='core_audit_action_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__target__a02965_idx',
            old_name='core_audit_model_target_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_audit__user_id_d9fe0d_idx',
            old_name='core_audit_user_created_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_info',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='详细信息'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='变更详情'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='变更后数据'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_data',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='变更前数据'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='目标模型'),
        ),
    ]
