# Generated by Django 5.2.15 on 2026-08-17 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_register_p2_monitor_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='例如：报表导出服务', max_length=100, verbose_name='标识用途')),
                ('key', models.CharField(help_text='仅签发时可见一次', max_length=128, unique=True, verbose_name='明文密钥')),
                ('key_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='SHA256 哈希')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '访问密钥',
                'verbose_name_plural': '访问密钥',
                'db_table': 'core_apikey',
                'ordering': ['-created_at'],
            },
        ),
    ]
