# Generated by Django 5.2.15 on 2026-08-31 09:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_apikey'),
        ('saas', '0007_role_data_scope_department_tenantmember_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='邮箱/账号')),
                ('ip', models.CharField(blank=True, max_length=100, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], db_index=True, default='success', max_length=20, verbose_name='状态')),
                ('failure_reason', models.CharField(blank=True, max_length=255, verbose_name='失败原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='登录时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='saas.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'core_login_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='idx_loginlog_tenant_created'), models.Index(fields=['status', 'created_at'], name='idx_loginlog_status_created')],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='邮箱/账号')),
                ('module', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='模块')),
                ('action', models.CharField(blank=True, max_length=100, verbose_name='动作')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='请求路径')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='状态码')),
                ('duration_ms', models.IntegerField(default=0, verbose_name='耗时(ms)')),
                ('ip', models.CharField(blank=True, max_length=100, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('request_summary', models.TextField(blank=True, verbose_name='请求摘要')),
                ('response_summary', models.TextField(blank=True, verbose_name='响应摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to='saas.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'core_operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='idx_oplog_tenant_created'), models.Index(fields=['module', 'created_at'], name='idx_oplog_module_created')],
            },
        ),
    ]
