# Generated by Django 5.2.15 on 2026-09-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_loginlog_operationlog'),
        ('saas', '0007_role_data_scope_department_tenantmember_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('code', models.CharField(max_length=100, verbose_name='字典编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统内置')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dict_types', to='saas.tenant', verbose_name='所属租户')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DictItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100, verbose_name='显示文本')),
                ('value', models.CharField(max_length=100, verbose_name='字典值')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dict_items', to='saas.tenant', verbose_name='所属租户')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.dicttype', verbose_name='字典类型')),
            ],
            options={
                'verbose_name': '字典项',
                'verbose_name_plural': '字典项',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dicttype',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_dict_type_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='dictitem',
            constraint=models.UniqueConstraint(fields=('tenant', 'type', 'value'), name='uq_dict_item_tenant_type_value'),
        ),
    ]
