# Generated by Django 5.2.15 on 2026-09-01 03:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dicts'),
        ('saas', '0007_role_data_scope_department_tenantmember_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('document', '文档'), ('image', '图片'), ('video', '视频'), ('audio', '音频')], default='document', max_length=20, verbose_name='资产分类')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(db_index=True, help_text='MEDIA_ROOT 下的绝对路径（保存产物）', max_length=500, verbose_name='存储路径')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='MIME 类型')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='软删标记；统计与配额均排除已删除资产', verbose_name='已删除')),
                ('tenant', models.ForeignKey(blank=True, help_text='空 = 无租户上下文上传（平台级/匿名登记）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_assets', to='saas.tenant', verbose_name='所属租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '文件资产',
                'verbose_name_plural': '文件资产',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'is_deleted'], name='idx_fileasset_tenant_deleted')],
            },
        ),
    ]
