# Generated by Django 5.2.15 on 2026-09-01 07:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_default_menus(apps, schema_editor):
    """播种默认菜单树（对应现有前端页面，幂等：表非空则跳过）。"""
    Menu = apps.get_model('core', 'Menu')
    if Menu.objects.exists():
        return

    backend = Menu.objects.create(
        name='工作台', route_name='backend', path='/backend',
        type='directory', icon='lucide:layout-dashboard', sort=10,
    )
    Menu.objects.create(
        parent=backend, name='AI 生成业务', route_name='backend-ai',
        path='/backend/ai', component='backend/ai', type='menu', sort=1,
    )
    Menu.objects.create(
        parent=backend, name='个人中心', route_name='backend-profile',
        path='/backend/profile', component='backend/profile', type='menu', sort=2,
    )
    Menu.objects.create(
        parent=backend, name='个人充值', route_name='backend-recharge',
        path='/backend/recharge', component='backend/recharge', type='menu', sort=3,
    )

    admin = Menu.objects.create(
        name='管理后台', route_name='admin', path='/admin',
        component='admin', type='menu', permission='system.manage',
        icon='lucide:settings', sort=20,
    )
    # 按钮级权限示例（前端 v-permission 使用，权限码对齐 PermissionSlug）
    Menu.objects.create(
        parent=admin, name='用户管理', route_name='admin-user',
        type='button', permission='user.manage', sort=1,
    )
    Menu.objects.create(
        parent=admin, name='角色管理', route_name='admin-role',
        type='button', permission='role.manage', sort=2,
    )

    Menu.objects.create(
        name='AI 创作', route_name='studio', path='/studio',
        component='studio', type='menu', icon='lucide:sparkles', sort=30,
    )
    Menu.objects.create(
        name='我的控制台', route_name='console', path='/console',
        component='console', type='menu', icon='lucide:user', sort=40,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fileasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('route_name', models.CharField(blank=True, max_length=100, verbose_name='路由名')),
                ('path', models.CharField(blank=True, help_text='前端路由路径，如 /backend/ai', max_length=200, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, help_text='前端组件路径，如 backend/ai', max_length=200, verbose_name='组件')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='图标')),
                ('type', models.CharField(choices=[('directory', '目录'), ('menu', '菜单'), ('button', '按钮')], db_index=True, default='menu', max_length=20, verbose_name='类型')),
                ('permission', models.CharField(blank=True, db_index=True, help_text='绑定 Permission.slug；目录/菜单为空 = 登录可见，按钮必填', max_length=100, verbose_name='权限码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='可见')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menu', verbose_name='上级菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'ordering': ['sort', 'created_at'],
                'indexes': [models.Index(fields=['type', 'is_active'], name='idx_menu_type_active')],
            },
        ),
        migrations.RunPython(seed_default_menus, migrations.RunPython.noop),
    ]
