# Generated by Django 5.2.15 on 2026-09-01 07:58

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_menu'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', '新增'), ('UPDATE', '修改'), ('DELETE', '删除'), ('LOGIN', '登录'), ('LOGOUT', '登出'), ('LOGIN_FAILED', '登录失败'), ('PERMISSION_CHANGE', '权限变更'), ('DATA_EXPORT', '数据导出'), ('SETTINGS_CHANGE', '配置变更'), ('PASSWORD_CHANGE', '密码变更'), ('OTHER', '其他')], max_length=20, verbose_name='操作行为')),
                ('log_type', models.CharField(choices=[('MODEL', '模型操作'), ('SENSITIVE', '敏感操作'), ('SYSTEM', '系统操作')], default='MODEL', max_length=10, verbose_name='日志类型')),
                ('target_model', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标模型')),
                ('target_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标ID')),
                ('old_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='变更前数据')),
                ('new_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='变更后数据')),
                ('changes', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='变更详情')),
                ('action_info', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, verbose_name='详细信息')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='浏览器指纹')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('data_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='数据哈希')),
                ('previous_hash', models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='上一条哈希')),
                ('is_tampered', models.BooleanField(default=False, verbose_name='是否被篡改')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='操作时间')),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='归档时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '审计日志归档',
                'verbose_name_plural': '审计日志归档',
                'db_table': 'core_audit_log_archive',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='core_audit__action_faf3fe_idx'), models.Index(fields=['user', 'created_at'], name='core_audit__user_id_12cccd_idx')],
            },
        ),
    ]
