# Generated by Django 5.2.15 on 2026-06-24 17:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at'], 'verbose_name': '发票', 'verbose_name_plural': '发票'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': '订单', 'verbose_name_plural': '订单'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ['module', 'slug'], 'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['sort_order', 'created_at'], 'verbose_name': '套餐', 'verbose_name_plural': '套餐'},
        ),
        migrations.AlterModelOptions(
            name='planfeature',
            options={'ordering': ['feature_code'], 'verbose_name': '套餐功能', 'verbose_name_plural': '套餐功能'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at'], 'verbose_name': '角色', 'verbose_name_plural': '角色'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['-created_at'], 'verbose_name': '租户', 'verbose_name_plural': '租户'},
        ),
        migrations.AlterModelOptions(
            name='tenantconfig',
            options={'ordering': ['category', 'key'], 'verbose_name': '租户配置', 'verbose_name_plural': '租户配置'},
        ),
        migrations.AlterModelOptions(
            name='tenantmember',
            options={'ordering': ['-joined_at'], 'verbose_name': '租户成员', 'verbose_name_plural': '租户成员'},
        ),
        migrations.AlterModelOptions(
            name='tenantsubscription',
            options={'ordering': ['-created_at'], 'verbose_name': '租户订阅', 'verbose_name_plural': '租户订阅'},
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='CNY', max_length=10, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='发票号'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='saas.order', verbose_name='订单'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='支付日期'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/', verbose_name='PDF 文件'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='saas.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='CNY', max_length=10, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('alipay', '支付宝'), ('wechat', '微信支付'), ('bank_transfer', '银行转账')], max_length=50, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='saas.plan', verbose_name='套餐'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('refunded', '已退款')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe 支付 ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='saas.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('tenant', '租户'), ('user', '用户'), ('billing', '计费'), ('analytics', '分析'), ('system', '系统')], max_length=50, verbose_name='模块'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='CNY', max_length=10, verbose_name='货币'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_storage_mb',
            field=models.IntegerField(default=1024, verbose_name='最大存储(MB)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='max_users',
            field=models.IntegerField(default=10, verbose_name='最大用户数'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='月价格'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='年价格'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='feature_code',
            field=models.CharField(max_length=100, verbose_name='功能代码'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='feature_name',
            field=models.CharField(max_length=100, verbose_name='功能名称'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='saas.plan', verbose_name='套餐'),
        ),
        migrations.AlterField(
            model_name='planfeature',
            name='value',
            field=models.CharField(blank=True, max_length=255, verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='role',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='是否系统角色'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', to='saas.permission', verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='saas.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='role',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='billing_date',
            field=models.DateField(blank=True, null=True, verbose_name='账单日期'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenants', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='domain',
            field=models.CharField(blank=True, max_length=255, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='saas.plan', verbose_name='套餐'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='标识'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('suspended', '已暂停'), ('cancelled', '已取消'), ('pending', '待开通')], default='active', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe 客户 ID'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='category',
            field=models.CharField(choices=[('general', '通用'), ('branding', '品牌'), ('security', '安全'), ('integration', '集成')], default='general', max_length=50, verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='key',
            field=models.CharField(max_length=100, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='saas.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tenantconfig',
            name='value',
            field=models.TextField(verbose_name='配置值'),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL, verbose_name='邀请者'),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='saas.role', verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='saas.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='tenantmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='auto_renew',
            field=models.BooleanField(default=True, verbose_name='自动续费'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='saas.plan', verbose_name='套餐'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='status',
            field=models.CharField(choices=[('active', '活跃'), ('cancelled', '已取消'), ('past_due', '已逾期'), ('trial', '试用中')], default='trial', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Stripe 订阅 ID'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='saas.tenant', verbose_name='租户'),
        ),
        migrations.AlterField(
            model_name='tenantsubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name'),
        ),
    ]
