# Generated by Django 6.0.6 on 2026-07-02 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0002_add_role_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILimitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('url_pattern', models.CharField(help_text='支持通配符匹配，如 /api/export/* 或正则 ^/saas/api/tenants/', max_length=500, verbose_name='URL 模式')),
                ('throttle_type', models.CharField(choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流')], default='ip', max_length=20, verbose_name='限流类型')),
                ('rate', models.CharField(default='100/h', help_text='格式: 次数/周期，如 100/h(每小时100次), 10/m(每分钟10次), 1000/d(每天1000次)', max_length=50, verbose_name='速率限制')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('use_regex', models.BooleanField(default=False, help_text='启用后 url_pattern 将作为正则表达式解析', verbose_name='使用正则匹配')),
                ('priority', models.IntegerField(default=0, help_text='数值越小优先级越高，用于多规则匹配时选择最优规则', verbose_name='优先级')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API 限流规则',
                'verbose_name_plural': 'API 限流规则',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
