# Generated by Django 6.0.6 on 2026-07-17 07:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0003_add_api_gateway_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(db_index=True, max_length=100, verbose_name='配置键')),
                ('config_type', models.CharField(max_length=50, verbose_name='配置类型')),
                ('operation', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('rollback', '回滚')], max_length=20, verbose_name='操作类型')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('diff', models.JSONField(blank=True, default=dict, verbose_name='差异详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '配置历史',
                'verbose_name_plural': '配置历史',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='唯一特性标识，如 feature.new_ui', max_length=100, unique=True, verbose_name='特性键')),
                ('name', models.CharField(max_length=200, verbose_name='特性名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('paused', '暂停'), ('archived', '已归档')], db_index=True, default='draft', max_length=20, verbose_name='状态')),
                ('rollout_strategy', models.CharField(choices=[('all', '全部用户'), ('internal', '仅内部用户'), ('percentage', '按比例'), ('users', '指定用户'), ('tenants', '指定租户'), ('user_groups', '指定用户组')], default='all', max_length=20, verbose_name='发布策略')),
                ('rollout_percentage', models.PositiveIntegerField(default=100, help_text='0-100，仅在 percentage 策略下生效', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='发布比例')),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, help_text='特性开始生效时间', null=True, verbose_name='开始时间')),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, help_text='特性结束生效时间', null=True, verbose_name='结束时间')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='额外的配置信息', verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feature_flags', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('target_tenants', models.ManyToManyField(blank=True, related_name='feature_flags', to='saas.tenant', verbose_name='目标租户')),
                ('target_users', models.ManyToManyField(blank=True, related_name='feature_flags', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_feature_flags', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '特性开关',
                'verbose_name_plural': '特性开关',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, help_text='唯一配置标识，推荐使用点号分隔，如 system.timeout', max_length=100, unique=True, verbose_name='配置键')),
                ('name', models.CharField(max_length=200, verbose_name='配置名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('value', models.TextField(help_text='存储配置的原始值', verbose_name='配置值')),
                ('config_type', models.CharField(choices=[('string', '字符串'), ('integer', '整数'), ('boolean', '布尔值'), ('float', '浮点数'), ('json', 'JSON对象')], default='string', max_length=20, verbose_name='类型')),
                ('category', models.CharField(choices=[('system', '系统配置'), ('feature', '功能配置'), ('business', '业务配置'), ('security', '安全配置')], default='system', max_length=50, verbose_name='分类')),
                ('default_value', models.TextField(blank=True, help_text='默认配置值', verbose_name='默认值')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('is_public', models.BooleanField(default=False, help_text='公开配置可被前端直接读取', verbose_name='是否公开')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_global_configs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_global_configs', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '全局配置',
                'verbose_name_plural': '全局配置',
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='ThrottleAlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('throttle_type', models.CharField(blank=True, choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流')], help_text='留空表示所有类型', max_length=20, verbose_name='限流类型')),
                ('threshold_count', models.IntegerField(default=10, help_text='达到此次数触发告警', verbose_name='阈值次数')),
                ('time_window', models.IntegerField(default=3600, help_text='在多少秒内达到阈值', verbose_name='时间窗口(秒)')),
                ('alert_level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='warning', max_length=20, verbose_name='告警级别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='throttle_alert_rules', to='saas.tenant', verbose_name='租户')),
                ('throttle_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='saas.apilimitrule', verbose_name='关联限流规则')),
            ],
            options={
                'verbose_name': '告警规则配置',
                'verbose_name_plural': '告警规则配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThrottleAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('rate_exceeded', '频率超限'), ('threshold_reached', '阈值告警'), ('anomaly_detected', '异常检测')], max_length=30, verbose_name='告警类型')),
                ('alert_level', models.CharField(choices=[('info', '信息'), ('warning', '警告'), ('error', '错误'), ('critical', '严重')], default='warning', max_length=20, verbose_name='告警级别')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('sent', '已发送'), ('acknowledged', '已确认'), ('resolved', '已解决')], default='pending', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='告警标题')),
                ('message', models.TextField(verbose_name='告警内容')),
                ('throttle_type', models.CharField(blank=True, choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流')], max_length=20, verbose_name='限流类型')),
                ('identifier', models.CharField(blank=True, max_length=255, verbose_name='限流标识')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('throttle_count', models.IntegerField(default=0, verbose_name='限流次数')),
                ('threshold', models.IntegerField(blank=True, null=True, verbose_name='告警阈值')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='发送时间')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_throttle_alerts', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_throttle_alerts', to=settings.AUTH_USER_MODEL, verbose_name='解决人')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='saas.apilimitrule', verbose_name='关联规则')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='throttle_alerts', to='saas.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '限流告警',
                'verbose_name_plural': '限流告警',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='saas_thrott_status_dda4fb_idx'), models.Index(fields=['alert_level', '-created_at'], name='saas_thrott_alert_l_9554aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThrottleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('throttle_type', models.CharField(choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流')], default='ip', max_length=20, verbose_name='限流类型')),
                ('identifier', models.CharField(help_text='IP地址/用户ID/租户ID等', max_length=255, verbose_name='限流标识')),
                ('path', models.CharField(max_length=500, verbose_name='请求路径')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('limit', models.IntegerField(blank=True, null=True, verbose_name='限制次数')),
                ('window_seconds', models.IntegerField(blank=True, null=True, verbose_name='窗口秒数')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='客户端IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='触发时间')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='throttle_logs', to='saas.apilimitrule', verbose_name='触发的规则')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='throttle_logs', to='saas.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='throttle_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '限流日志',
                'verbose_name_plural': '限流日志',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['throttle_type', '-created_at'], name='saas_thrott_throttl_078e67_idx'), models.Index(fields=['identifier', '-created_at'], name='saas_thrott_identif_e0cc1a_idx'), models.Index(fields=['-created_at'], name='saas_thrott_created_2f4d0b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThrottleStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('minute', '分钟'), ('hour', '小时'), ('day', '天')], default='hour', max_length=10, verbose_name='统计周期')),
                ('period_start', models.DateTimeField(db_index=True, verbose_name='周期开始时间')),
                ('throttle_type', models.CharField(choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流')], default='ip', max_length=20, verbose_name='限流类型')),
                ('identifier', models.CharField(blank=True, max_length=255, verbose_name='限流标识')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='请求路径')),
                ('request_count', models.IntegerField(default=0, verbose_name='总请求数')),
                ('throttle_count', models.IntegerField(default=0, verbose_name='被限流次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='saas.apilimitrule', verbose_name='限流规则')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='throttle_stats', to='saas.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '限流统计',
                'verbose_name_plural': '限流统计',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['period', 'period_start'], name='saas_thrott_period_7363f6_idx'), models.Index(fields=['throttle_type', '-period_start'], name='saas_thrott_throttl_1d2a1d_idx')],
                'unique_together': {('period', 'period_start', 'throttle_type', 'identifier', 'path', 'tenant')},
            },
        ),
    ]
