# Generated by Django 5.2.15 on 2026-08-31 09:15

from django.db import migrations, models


def backfill_is_default(apps, schema_editor):
    """幂等回填：对每个用户，若尚无默认成员，把最早加入的活跃成员置为默认租户。

    对齐参考项目语义：登录时默认进入 is_default 租户；存量数据平滑过渡。
    """
    TenantMember = apps.get_model("saas", "TenantMember")
    User = apps.get_model("users", "User")
    for user in User.objects.all().iterator():
        if TenantMember.objects.filter(user_id=user.id, is_default=True).exists():
            continue
        first_active = (
            TenantMember.objects.filter(user_id=user.id, is_active=True)
            .order_by("joined_at", "id")
            .first()
        )
        if first_active is not None:
            first_active.is_default = True
            first_active.save(update_fields=["is_default"])


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0004_confighistory_featureflag_globalconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmember',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='默认租户'),
        ),
        migrations.AlterField(
            model_name='apilimitrule',
            name='throttle_type',
            field=models.CharField(choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流'), ('anon', '匿名限流')], default='ip', max_length=20, verbose_name='限流类型'),
        ),
        migrations.AlterField(
            model_name='throttlealert',
            name='throttle_type',
            field=models.CharField(blank=True, choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流'), ('anon', '匿名限流')], max_length=20, verbose_name='限流类型'),
        ),
        migrations.AlterField(
            model_name='throttlealertrule',
            name='throttle_type',
            field=models.CharField(blank=True, choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流'), ('anon', '匿名限流')], help_text='留空表示所有类型', max_length=20, verbose_name='限流类型'),
        ),
        migrations.AlterField(
            model_name='throttlelog',
            name='throttle_type',
            field=models.CharField(choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流'), ('anon', '匿名限流')], default='ip', max_length=20, verbose_name='限流类型'),
        ),
        migrations.AlterField(
            model_name='throttlestats',
            name='throttle_type',
            field=models.CharField(choices=[('ip', 'IP 限流'), ('user', '用户限流'), ('tenant', '租户限流'), ('endpoint', '端点限流'), ('anon', '匿名限流')], default='ip', max_length=20, verbose_name='限流类型'),
        ),
        migrations.RunPython(backfill_is_default, migrations.RunPython.noop),
    ]
