# Generated by Django 5.2.15 on 2026-08-31 09:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def backfill_default_plan(apps, schema_editor):
    """无默认套餐时，取第一个套餐标记为默认；连套餐都没有则创建 standard
    默认套餐（对齐参考项目 ensure_default_tenant_plan）。幂等。"""
    Plan = apps.get_model('saas', 'Plan')
    if Plan.objects.filter(is_default=True).exists():
        return
    first = Plan.objects.order_by('sort_order', 'created_at').first()
    if first is not None:
        first.is_default = True
        first.save(update_fields=['is_default'])
        return
    Plan.objects.create(
        slug='standard',
        name='标准版',
        description='默认套餐：不限文件资产数量，适合绝大多数租户。',
        price=0,
        price_yearly=0,
        currency='CNY',
        max_users=100,
        max_storage_mb=10240,
        max_file_assets=1000,
        is_default=True,
        is_active=True,
        is_featured=False,
        sort_order=0,
    )


def seed_default_template(apps, schema_editor):
    """创建默认初始化模板 code='standard'（对齐参考项目），幂等。"""
    TenantInitializationTemplate = apps.get_model('saas', 'TenantInitializationTemplate')
    if TenantInitializationTemplate.objects.filter(code='standard').exists():
        return
    TenantInitializationTemplate.objects.create(
        code='standard',
        name='标准模板',
        description='标准租户初始化模板：创建总部根部门并全量初始化 7 类种子数据。',
        root_department_code='headquarters',
        root_department_name='总部',
        seed_posts=True,
        seed_dictionaries=True,
        seed_settings=True,
        seed_storage_channels=True,
        seed_message_templates=True,
        seed_sms_channels=True,
        seed_mail_accounts=True,
        is_default=True,
        is_active=True,
    )


def backfill_tenant_profiles(apps, schema_editor):
    """为存量无档案的租户补齐 TenantProfile（formal + effective_at=now），幂等。"""
    Tenant = apps.get_model('saas', 'Tenant')
    TenantProfile = apps.get_model('saas', 'TenantProfile')
    now = timezone.now()
    for tenant in Tenant.objects.filter(profile__isnull=True):
        TenantProfile.objects.create(
            tenant=tenant,
            lifecycle_status='formal',
            effective_at=now,
        )


def backfill_plan_profiles(apps, schema_editor):
    """为存量套餐补齐 TenantPlanProfile，并按订阅/已支付订单回填统计（幂等）。"""
    Plan = apps.get_model('saas', 'Plan')
    TenantPlanProfile = apps.get_model('saas', 'TenantPlanProfile')
    TenantSubscription = apps.get_model('saas', 'TenantSubscription')
    Order = apps.get_model('saas', 'Order')

    for idx, plan in enumerate(Plan.objects.order_by('sort_order', 'created_at'), start=1):
        profile, created = TenantPlanProfile.objects.get_or_create(
            plan=plan, defaults={'order_num': idx}
        )
        if created:
            profile.subscription_num = TenantSubscription.objects.filter(plan=plan).count()
            paid_total = Order.objects.filter(
                plan=plan, status='paid'
            ).aggregate(
                total=models.Sum('amount'),
            )['total']
            profile.subscription_total_amount = paid_total or 0
            profile.save(update_fields=[
                'subscription_num', 'subscription_total_amount', 'updated_at',
            ])


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_tenantmember_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantInitializationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=100, unique=True, verbose_name='模板编码')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('root_department_code', models.CharField(default='headquarters', max_length=100, verbose_name='根部门编码')),
                ('root_department_name', models.CharField(default='总部', max_length=100, verbose_name='根部门名称')),
                ('seed_posts', models.BooleanField(default=True, verbose_name='种子：岗位')),
                ('seed_dictionaries', models.BooleanField(default=True, verbose_name='种子：字典')),
                ('seed_settings', models.BooleanField(default=True, verbose_name='种子：设置')),
                ('seed_storage_channels', models.BooleanField(default=True, verbose_name='种子：存储渠道')),
                ('seed_message_templates', models.BooleanField(default=True, verbose_name='种子：消息模板')),
                ('seed_sms_channels', models.BooleanField(default=True, verbose_name='种子：短信渠道')),
                ('seed_mail_accounts', models.BooleanField(default=True, verbose_name='种子：邮箱账户')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '租户初始化模板',
                'verbose_name_plural': '租户初始化模板',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPlanProfile',
            fields=[
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='saas.plan', verbose_name='套餐')),
                ('package_type', models.IntegerField(default=0, verbose_name='套餐类型')),
                ('logo', models.CharField(blank=True, max_length=500, verbose_name='Logo')),
                ('published', models.IntegerField(default=0, verbose_name='上架状态')),
                ('order_num', models.IntegerField(default=1, verbose_name='排序')),
                ('subscription_num', models.IntegerField(default=0, verbose_name='订阅数')),
                ('subscription_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订阅总金额')),
                ('remark', models.CharField(blank=True, max_length=500, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '套餐档案',
                'verbose_name_plural': '套餐档案',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='默认套餐'),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_file_assets',
            field=models.IntegerField(default=100, verbose_name='最大文件资产数'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='initialization_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='saas.tenantinitializationtemplate', verbose_name='初始化模板'),
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='saas.tenant', verbose_name='租户')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='联系人姓名')),
                ('contact_mobile', models.CharField(blank=True, max_length=32, verbose_name='联系人手机')),
                ('industry', models.IntegerField(blank=True, null=True, verbose_name='行业')),
                ('tenant_type', models.IntegerField(blank=True, null=True, verbose_name='租户类型')),
                ('address_code', models.CharField(blank=True, max_length=100, verbose_name='地区编码')),
                ('address_detail', models.CharField(blank=True, max_length=255, verbose_name='详细地址')),
                ('qualifications', models.CharField(blank=True, max_length=500, verbose_name='资质')),
                ('website', models.CharField(blank=True, max_length=255, verbose_name='官网')),
                ('recharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='充值金额')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='消费金额')),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='余额')),
                ('account_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='账户数')),
                ('lifecycle_status', models.CharField(choices=[('trial', '试用'), ('formal', '正式'), ('frozen', '冻结'), ('expired', '已过期'), ('archived', '已归档')], db_index=True, default='formal', max_length=20, verbose_name='生命周期状态')),
                ('lifecycle_status_before_freeze', models.CharField(blank=True, choices=[('trial', '试用'), ('formal', '正式'), ('frozen', '冻结'), ('expired', '已过期'), ('archived', '已归档')], max_length=20, null=True, verbose_name='冻结前状态')),
                ('effective_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('trial_ends_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='试用截止时间')),
                ('service_expires_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='服务到期时间')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='冻结时间')),
                ('frozen_reason', models.CharField(blank=True, max_length=500, null=True, verbose_name='冻结原因')),
                ('owner_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='客户负责人')),
                ('customer_source', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='客户来源')),
                ('follow_up_notes', models.CharField(blank=True, max_length=1000, verbose_name='跟进备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_profiles_contact', to=settings.AUTH_USER_MODEL, verbose_name='联系人')),
            ],
            options={
                'verbose_name': '租户档案',
                'verbose_name_plural': '租户档案',
            },
        ),
        migrations.RunPython(backfill_default_plan, migrations.RunPython.noop),
        migrations.RunPython(seed_default_template, migrations.RunPython.noop),
        migrations.RunPython(backfill_tenant_profiles, migrations.RunPython.noop),
        migrations.RunPython(backfill_plan_profiles, migrations.RunPython.noop),
    ]
