# Generated by Django 5.2.15 on 2026-08-31 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_role_data_scope(apps, schema_editor):
    """存量角色数据权限回填：super-admin/admin 全局 → all，其余保持默认 self。"""
    Role = apps.get_model('saas', 'Role')
    for role in Role.objects.all():
        if role.slug in ('super-admin', 'admin') and role.data_scope != 'all':
            role.data_scope = 'all'
            role.save(update_fields=['data_scope'])


def seed_org_for_existing_tenants(apps, schema_editor):
    """存量租户补齐组织种子：根部门 + 默认岗位（幂等，对齐初始化模板）。"""
    Tenant = apps.get_model('saas', 'Tenant')
    Department = apps.get_model('saas', 'Department')
    Post = apps.get_model('saas', 'Post')

    DEFAULT_POSTS = (
        ('manager', '经理', 10),
        ('developer', '开发工程师', 20),
        ('operator', '运营专员', 30),
    )

    for tenant in Tenant.objects.all():
        template = tenant.initialization_template
        root_code = (template.root_department_code if template else None) or 'headquarters'
        root_name = (template.root_department_name if template else None) or '总部'
        Department.objects.get_or_create(
            tenant=tenant, code=root_code,
            defaults={'name': root_name, 'sort': 0},
        )
        if template is None or template.seed_posts:
            for code, name, sort in DEFAULT_POSTS:
                Post.objects.get_or_create(
                    tenant=tenant, code=code,
                    defaults={'name': name, 'sort': sort},
                )


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0006_tenantinitializationtemplate_tenantplanprofile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='data_scope',
            field=models.CharField(choices=[('all', '全部数据'), ('department', '本部门数据'), ('department_and_children', '本部门及子部门数据'), ('self', '仅本人数据'), ('custom', '自定义部门数据')], db_index=True, default='self', max_length=32, verbose_name='数据权限'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('leader_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_departments', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='saas.department', verbose_name='上级部门')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='saas.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'ordering': ['sort', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='tenantmember',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='saas.department', verbose_name='部门'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(max_length=100, verbose_name='编码')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='归档时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='saas.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'ordering': ['sort', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleDataScopeDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scope_roles', to='saas.department', verbose_name='部门')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scope_departments', to='saas.role', verbose_name='角色')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scope_links', to='saas.tenant', verbose_name='租户')),
            ],
            options={
                'verbose_name': '角色数据权限部门',
                'verbose_name_plural': '角色数据权限部门',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='saas.post', verbose_name='岗位')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to='saas.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_posts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户岗位',
                'verbose_name_plural': '用户岗位',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['tenant', 'archived_at'], name='idx_department_tenant_archived'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_department_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['tenant', 'archived_at'], name='idx_post_tenant_archived'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_post_tenant_code'),
        ),
        migrations.AddConstraint(
            model_name='roledatascopedepartment',
            constraint=models.UniqueConstraint(fields=('tenant', 'role', 'department'), name='uq_roledatascope_tenant_role_dept'),
        ),
        migrations.AddConstraint(
            model_name='userpost',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'post'), name='uq_userpost_tenant_user_post'),
        ),
        migrations.RunPython(backfill_role_data_scope, migrations.RunPython.noop),
        migrations.RunPython(seed_org_for_existing_tenants, migrations.RunPython.noop),
    ]
