# Generated by Django 5.2.8 on 2026-05-28 03:22

from django.db import migrations

from system.users.models import CustomUserManager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', CustomUserManager()),
            ],
        ),
    ]
