# Generated by Django 5.2.8 on 2026-07-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_old_role_add_new_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
    ]
