# Generated by Django 5.2.15 on 2026-08-31 09:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0005_tenantmember_is_default_and_more'),
        ('users', '0011_user_token_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_jti', models.CharField(db_index=True, max_length=64, verbose_name='Token JTI')),
                ('ip', models.CharField(blank=True, max_length=64, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='User-Agent')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='吊销时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='saas.tenant', verbose_name='租户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户会话',
                'verbose_name_plural': '用户会话',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'token_jti'], name='users_users_user_id_9c6d0b_idx'), models.Index(fields=['user', 'revoked_at'], name='users_users_user_id_06db0b_idx')],
            },
        ),
    ]
