# Generated by Django 5.2.15 on 2026-09-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='MFA 确认时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_enabled',
            field=models.BooleanField(default=False, verbose_name='MFA 已启用'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_recovery_code_hashes',
            field=models.TextField(blank=True, null=True, verbose_name='MFA 恢复码哈希'),
        ),
        migrations.AddField(
            model_name='user',
            name='mfa_secret_encrypted',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MFA 密钥(加密)'),
        ),
    ]
