# Generated by Django 5.2.15 on 2026-09-01 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_mfa'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='提供方标识')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='显示名称')),
                ('client_id', models.CharField(max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=255, verbose_name='Client Secret')),
                ('authorize_url', models.URLField(max_length=500, verbose_name='授权端点')),
                ('token_url', models.URLField(max_length=500, verbose_name='Token 端点')),
                ('userinfo_url', models.URLField(max_length=500, verbose_name='用户信息端点')),
                ('scope', models.CharField(blank=True, help_text='授权范围，如 "read:user user:email"；留空则不传 scope 参数', max_length=255, verbose_name='Scope')),
                ('redirect_uri', models.CharField(blank=True, help_text='留空则按当前请求动态生成（/api/v1/users/oauth/{name}/callback/）', max_length=500, verbose_name='回调地址')),
                ('pkce_enabled', models.BooleanField(default=True, help_text='授权码模式强制 PKCE（S256），防止授权码截获重放', verbose_name='启用 PKCE')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'OAuth2 提供方',
                'verbose_name_plural': 'OAuth2 提供方',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_uid', models.CharField(max_length=255, verbose_name='第三方唯一标识')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='第三方邮箱')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='原始资料')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='users.oauthprovider', verbose_name='提供方')),
            ],
            options={
                'verbose_name': 'OAuth2 绑定',
                'verbose_name_plural': 'OAuth2 绑定',
                'indexes': [models.Index(fields=['user', 'provider'], name='users_oauth_user_id_8c7d58_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_uid'), name='uniq_oauth_provider_uid')],
            },
        ),
    ]
