# Generated by Django 5.2.15 on 2026-09-01 07:16

import framework.security.sensitive
from django.db import migrations


def encrypt_existing_secrets(apps, schema_editor):
    """加密存量明文 client_secret（在 AlterField 前执行，模型仍是 CharField，
    ORM 读到的还是明文，不会触发 SensitiveField 解密；已是 v1: 密文则跳过，保证幂等）。"""
    from framework.security.sensitive import encrypt_value

    OAuthProvider = apps.get_model("users", "OAuthProvider")
    for provider in OAuthProvider.objects.all().iterator():
        raw = provider.client_secret
        if raw and not raw.startswith("v1:"):
            provider.client_secret = encrypt_value(raw)
            provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_oauthprovider_oauthaccount'),
    ]

    operations = [
        migrations.RunPython(encrypt_existing_secrets, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='oauthprovider',
            name='client_secret',
            field=framework.security.sensitive.SensitiveField(max_length=255, verbose_name='Client Secret'),
        ),
    ]
