# Generated by Django 5.2.17 on 2026-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildtask',
            name='apk_type',
            field=models.CharField(choices=[('custom', '自定义 APK')], default='custom', max_length=20),
        ),
    ]
