# Generated by Django 5.2.15 on 2026-08-03 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('kind', models.CharField(choices=[('IMAGE', '图片'), ('VIDEO', '视频')], default='IMAGE', max_length=10, verbose_name='类型')),
                ('prompt', models.TextField(blank=True, verbose_name='描述需求')),
                ('ref_image', models.TextField(blank=True, null=True, verbose_name='参考图(base64/url)')),
                ('style', models.CharField(blank=True, default='', max_length=30, verbose_name='风格')),
                ('size', models.CharField(blank=True, default='1:1', max_length=10, verbose_name='尺寸')),
                ('resolution', models.CharField(blank=True, default='standard', max_length=10, verbose_name='分辨率')),
                ('count', models.IntegerField(default=1, verbose_name='数量')),
                ('cost', models.IntegerField(default=0, verbose_name='消耗额度')),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('RUNNING', '生成中'), ('SUCCESS', '成功'), ('FAILED', '失败')], default='PENDING', max_length=10, verbose_name='状态')),
                ('result_urls', models.JSONField(blank=True, default=list, verbose_name='生成结果')),
                ('error_msg', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('celery_task_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Celery任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '生成任务',
                'verbose_name_plural': '生成任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('GRANT', '赠送'), ('FREEZE', '冻结'), ('CONFIRM', '确认扣减'), ('REFUND', '返还')], max_length=10, verbose_name='类型')),
                ('amount', models.IntegerField(verbose_name='变动额度')),
                ('balance_after', models.IntegerField(verbose_name='变动后可用')),
                ('frozen_after', models.IntegerField(verbose_name='变动后冻结')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ai_studio.generationtask', verbose_name='关联任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota_tx', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '额度流水',
                'verbose_name_plural': '额度流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='可用额度')),
                ('frozen', models.IntegerField(default=0, verbose_name='冻结额度')),
                ('total_granted', models.IntegerField(default=0, verbose_name='累计获得额度')),
                ('signup_granted', models.BooleanField(default=False, verbose_name='已发放注册赠送')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_quota', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI 额度',
                'verbose_name_plural': 'AI 额度',
            },
        ),
    ]
