# Generated by Django 5.2.15 on 2026-08-03 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotatransaction',
            name='tx_type',
            field=models.CharField(choices=[('GRANT', '赠送'), ('RECHARGE', '充值'), ('ADMIN_GRANT', '管理员发放'), ('ADMIN_DEDUCT', '管理员扣减'), ('FREEZE', '冻结'), ('CONFIRM', '确认扣减'), ('REFUND', '返还')], max_length=16, verbose_name='类型'),
        ),
        migrations.CreateModel(
            name='RechargeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True, verbose_name='订单号')),
                ('quota_amount', models.IntegerField(verbose_name='充值额度')),
                ('status', models.CharField(choices=[('PENDING', '待支付'), ('PAID', '已支付'), ('CANCELLED', '已取消')], default='PENDING', max_length=10, verbose_name='状态')),
                ('method', models.CharField(default='mock', max_length=20, verbose_name='支付方式')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recharge_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '充值订单',
                'verbose_name_plural': '充值订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
