# Generated by Django 5.2.15 on 2026-08-03 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0002_alter_quotatransaction_tx_type_rechargeorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('kind', models.CharField(choices=[('API', 'API 渠道'), ('AGENT', '自建 Agent')], default='API', max_length=10, verbose_name='类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否对用户开放')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('cost_per_call', models.PositiveIntegerField(default=0, verbose_name='每次调用消耗额度(按张)')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='配置(端点/模型/密钥引用)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API 渠道/Agent',
                'verbose_name_plural': 'API 渠道/Agent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='generationtask',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ai_studio.apichannel', verbose_name='关联渠道/Agent'),
        ),
        migrations.CreateModel(
            name='UserChannelGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否允许使用')),
                ('per_user_quota', models.PositiveIntegerField(blank=True, null=True, verbose_name='专属额度上限(可选, 按累计消耗计)')),
                ('used_quota', models.PositiveIntegerField(default=0, verbose_name='已用额度(累计消耗)')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='ai_studio.apichannel', verbose_name='渠道/Agent')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='授权人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_grants', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户渠道授权',
                'verbose_name_plural': '用户渠道授权',
                'unique_together': {('user', 'channel')},
            },
        ),
    ]
