# Generated by Django 5.2.15 on 2026-08-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0003_apichannel_generationtask_channel_userchannelgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='external_task_id',
            field=models.CharField(blank=True, help_text='第三方异步任务标识（如 Veo operation name），便于回调/查询', max_length=255, null=True, verbose_name='第三方任务ID'),
        ),
    ]
