# Generated by Django 5.2.15 on 2026-08-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0004_generationtask_external_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='first_frame',
            field=models.ImageField(blank=True, help_text='视频生成时由用户上传的首帧图像（image-to-video），优先于 ref_image 与自动出图', null=True, upload_to='ai_studio/first_frames/', verbose_name='视频首帧(上传)'),
        ),
    ]
