# Generated by Django 5.2.15 on 2026-08-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_studio', '0005_generationtask_first_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='error_code',
            field=models.CharField(blank=True, help_text='标准化错误码（如 API_KEY_INVALID/QUOTA_EXCEEDED/NO_FIRST_FRAME），对应 error 对象', max_length=64, null=True, verbose_name='错误码'),
        ),
    ]
